"""Add upload_session field to UploadedFile

Revision ID: 1ca96f0a8064
Revises: fdf0a06e3425
Create Date: 2025-10-21 11:06:47.997000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ca96f0a8064'
down_revision: Union[str, Sequence[str], None] = 'fdf0a06e3425'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    import uuid

    # First add the column as nullable
    op.add_column('uploaded_files', sa.Column('upload_session', sa.UUID(), nullable=True))

    # Update existing rows with a default UUID
    # We need to use raw SQL since we're modifying data
    conn = op.get_bind()

    # Generate a single shared UUID for all existing files (since they don't belong to any specific upload session)
    shared_session_id = uuid.uuid4()
    conn.execute(sa.text(f"UPDATE uploaded_files SET upload_session = '{shared_session_id}'"))

    # Now alter the column to be non-nullable
    op.alter_column('uploaded_files', 'upload_session', nullable=False)

    # Create index after data is properly set
    op.create_index(op.f('ix_uploaded_files_upload_session'), 'uploaded_files', ['upload_session'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_uploaded_files_upload_session'), table_name='uploaded_files')
    op.drop_column('uploaded_files', 'upload_session')
    # ### end Alembic commands ###
