"""Add tags field to UploadedFile

Revision ID: fdf0a06e3425
Revises: 50ca5a5650ac
Create Date: 2025-10-21 10:33:21.928867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdf0a06e3425'
down_revision: Union[str, Sequence[str], None] = '50ca5a5650ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uploaded_files', sa.Column('tags', sa.JSON(), nullable=True))
    op.create_unique_constraint(None, 'uploaded_files', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'uploaded_files', type_='unique')
    op.drop_column('uploaded_files', 'tags')
    # ### end Alembic commands ###
